Add --force for script/update.

diff --git a/script/update b/script/update
--- a/script/update
+++ b/script/update
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [[ $1 == '--force' ]]; then
+  shift
+  FORCE_UPDATE='yes'
+fi
+
 MODE=${1:-'Release'}
 
 # Root of cefode
@@ -13,14 +18,17 @@ if [ ! -d "$ROOT/src" ]; then
 fi
 
 progress 'Updating source code'
-cd "$ROOT/src"
-CURRENT_HEAD=`git log -1 | head -n 1 | awk '{ print $2 }'`
-REMOTE_HEAD=`git ls-remote origin -h refs/heads/master | awk '{ print $1 }'`
-if [[ $? -ne 0 ]]; then
-  fail 'Cannot get remote head'
-elif [[ $REMOTE_HEAD == $CURRENT_HEAD ]]; then
-  success 'Already at the newest commit'
-  exit
+
+if [ -z $FORCE_UPDATE ]; then
+  cd "$ROOT/src"
+  CURRENT_HEAD=`git log -1 | head -n 1 | awk '{ print $2 }'`
+  REMOTE_HEAD=`git ls-remote origin -h refs/heads/master | awk '{ print $1 }'`
+  if [[ $? -ne 0 ]]; then
+    fail 'Cannot get remote head'
+  elif [[ $REMOTE_HEAD == $CURRENT_HEAD ]]; then
+    success 'Already at the newest commit'
+    exit
+  fi
 fi
 
 [[ $PLATFORM == 'darwin' ]] || export GYP_GENERATORS=ninja 
